## Wiskunde II - portfolio

groepsnummer: 7

studenten: Baset Paiman (24071005), Sharina Nasrullah (25103083), Shelby Gibbs (18005055).

##### import libraries

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

##### dataset inladen

In [2]:
df = pd.read_excel("Mobiliteitsdata.xlsx")
df.head(5)

,persoon_ID,geslacht,leeftijd,gewicht_KG,burgerlijke_staat,jaarsalaris_eu,huishouden_grootte,stad,provincie,opleiding_niveau,...,elektrisch_auto,km_auto_per_jaar,km_fiets_per_jaar,km_ov_per_jaar,km_vliegtuig_per_jaar,dagen_thuiswerken_per_week_pro_rato,dagen_kantoorwerken_per_week_pro_rato,dagen_in_buitenland_per_jaar,gebruik_carsharing,co2_uitstoot_per_jaar_KG
0,811069,man,50,52.66,weduwe/weduwnaar,48003.64,5,Almere,Flevoland,MBO,...,nee,13266.05,2040.54,3227.95,480.71,4,1,20,Nooit,7591.93
1,246882,vrouw,65,64.58,samenwonend,55208.63,2,Leeuwarden,Overijssel,WO,...,nee,15229.89,0.00,2298.96,1423.34,5,0,7,Heel soms,8742.25
2,978385,man,49,90.87,samenwonend,29533.78,2,Tilburg,Utrecht,HBO,...,ja,19853.24,1540.46,4504.21,632.48,4,1,2,Altijd,4513.56
3,120468,man,34,80.43,gehuwd,44453.27,2,Maastricht,Utrecht,HBO,...,nee,9935.50,1825.92,4407.56,1266.84,3,2,21,Heel soms,6904.41
4,637034,man,60,72.28,ongehuwd,56497.64,2,Leiden,Gelderland,MBO,...,ja,16266.67,1851.07,1936.12,1676.00,0,5,0,Nooit,4420.80

nominale variabelen: persoon_ID, geslacht, burgerlijke_staat, stad, provincie, autobezit, fietsbezit en elektrisch_auto.

ordinale variabelen: opleiding_niveau en gebruik_carsharing

interval variabelen: geen 

ratio: leeftijd, gewicht_KG, jaarsalaris_eu, huishouden_grootte, km_auto_per_jaar, km_fiets_per_jaar, km_ov_per_jaar, km_vliegtuig_per_jaar, dagen_thuiswerken_per_week_pro_rato,  dagen_kantoorwerken_per_week_pro_rato, dagen_in_buitenland_per_jaar, co2_uitstoot_per_jaar_KG

#### opdracht 2 - 

Waarom is het nodig om vooraf te bekijken tot welk meetniveau elke variabele behoort?

het meetniveau bepaalt welke statistiche bewerkingen, analyses en visualisaties op een variabele mogen worden toegepast. hierdoor worden verkeerde analyses en conclusies voorkomen.

### relevante statistieken

##### ratio variabelen

In [5]:
ratio_variabelen= [
    'leeftijd',
    'gewicht_KG', 
    'jaarsalaris_eu', 
    'huishouden_grootte', 
    'km_auto_per_jaar', 
    'km_fiets_per_jaar',
    'km_ov_per_jaar',
    'km_vliegtuig_per_jaar',
    'dagen_thuiswerken_per_week_pro_rato',
    'dagen_kantoorwerken_per_week_pro_rato',
    'dagen_in_buitenland_per_jaar',
    'co2_uitstoot_per_jaar_KG'] 

display(df[ratio_variabelen].describe())

,leeftijd,gewicht_KG,jaarsalaris_eu,huishouden_grootte,km_auto_per_jaar,km_fiets_per_jaar,km_ov_per_jaar,km_vliegtuig_per_jaar,dagen_thuiswerken_per_week_pro_rato,dagen_kantoorwerken_per_week_pro_rato,dagen_in_buitenland_per_jaar,co2_uitstoot_per_jaar_KG
count,1500.000000,1500.00000,1499.000000,1500.000000,1500.000000,1500.000000,1500.000000,1500.000000,1500.000000,1500.000000,1500.000000,1493.000000
mean,47.989333,75.14630,40092.551094,3.032000,8597.262393,1794.180353,2942.222840,1072.277327,2.532667,2.467333,14.485333,4912.341875
std,18.134915,14.79674,14986.839768,1.411017,7021.428530,753.991154,1531.377214,748.651072,1.671365,1.671365,8.700819,3422.902397
min,0.000000,0.00000,-8505.150000,1.000000,-6506.630000,0.000000,-2264.780000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,32.000000,65.63500,30008.920000,2.000000,0.000000,1503.420000,1950.682500,471.540000,1.000000,1.000000,7.000000,1469.450000
50%,47.000000,75.79000,40503.080000,3.000000,9356.380000,1910.005000,2987.030000,1052.140000,3.000000,2.000000,15.000000,4677.280000
75%,64.000000,84.93500,50281.165000,4.000000,13842.732500,2286.180000,3991.537500,1588.555000,4.000000,4.000000,22.000000,7481.550000
max,79.000000,117.76000,93826.850000,5.000000,34618.870000,3672.700000,8018.060000,3808.200000,5.000000,5.000000,29.000000,18098.440000

##### categorische variabelen

In [9]:
categorie_variabelen= [
    'geslacht',
    'burgerlijke_staat',
    'stad',
    'provincie',
    'opleiding_niveau',
    'autobezit',
    'fietsbezit',
    'elektrisch_auto',
    'gebruik_carsharing'
]

for kolom in categorie_variabelen:
    print(f"\n==== {kolom} ====")
    print(df[kolom].value_counts())

==== geslacht ====
geslacht
vrouw     778
man       720
anders      2
Name: count, dtype: int64

==== burgerlijke_staat ====
burgerlijke_staat
gehuwd              312
gescheiden          310
ongehuwd            310
weduwe/weduwnaar    287
samenwonend         281
Name: count, dtype: int64

==== stad ====
stad
Breda         72
Amsterdam     72
Enschede      67
Nijmegen      67
Utrecht       67
Venlo         66
Tilburg       62
Den Bosch     62
Leeuwarden    62
Middelburg    62
Leiden        61
Maastricht    61
Groningen     60
Zutphen       60
Eindhoven     60
Amersfoort    59
Rotterdam     57
Zwolle        56
Delft         54
Haarlem       54
Apeldoorn     54
Arnhem        53
Hoofddorp     52
Assen         51
Almere        48
Name: count, dtype: int64

==== provincie ====
provincie
Groningen        157
Flevoland        142
Limburg          140
Zeeland          130
Noord-Holland    125
Drenthe          125
Overijssel       124
Utrecht          118
Friesland        118
Gelderland       111
Noord-Brabant    106
Zuid-Holland     104
Name: count, dtype: int64

==== opleiding_niveau ====
opleiding_niveau
HBO    533
MBO    493
WO     473
Name: count, dtype: int64

==== autobezit ====
autobezit
ja     1066
nee     433
Name: count, dtype: int64

==== fietsbezit ====
fietsbezit
ja     1356
nee     144
Name: count, dtype: int64

==== elektrisch_auto ====
elektrisch_auto
nee    1210
ja      290
Name: count, dtype: int64

==== gebruik_carsharing ====
gebruik_carsharing
Nooit        911
Heel soms    239
Soms         144
Vaak         132
Altijd        74
Name: count, dtype: int64

##### modus

In [10]:
for kolom in categorie_variabelen:
    print(f"{kolom}: {df[kolom].mode()[0]}")

geslacht: vrouw
burgerlijke_staat: gehuwd
stad: Amsterdam
provincie: Groningen
opleiding_niveau: HBO
autobezit: ja
fietsbezit: ja
elektrisch_auto: nee
gebruik_carsharing: Nooit